name: Update Downloads Zip

on:
  push:
    paths:
      - 'downloads/**'

jobs:
  update-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Remove old downloads.zip
      run: |
        if [ -f downloads.zip ]; then
          rm downloads.zip
        fi

    - name: Create new downloads.zip
      run: |
        zip -r downloads.zip downloads/

    - name: Commit and push new downloads.zip
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add downloads.zip
        git commit -m 'Update downloads.zip'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
